---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/athorp96/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-update-osp-staging-dev
